#! /bin/dash
#
# TODO: https://www.reddit.com/r/bspwm/comments/ggtwxa/guide_to_creating_startup_layout_using_receptacles/
# https://github.com/windelicato/dotfiles/wiki/bspwm-for-dummies
# https://www.reddit.com/r/unixporn/comments/gftc5o/oc_realtime_websearch_suggestions_for_rofi_extras/

sxhkd &
bspc monitor DP-1 -d 1 2 3
bspc monitor eDP-1 -d 4 5 6 7
bspc monitor DP-1 -d 8 9 0

# border configuration
bspc config border_width         2
bspc config window_gap          20
bspc config top_padding          0
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0
bspc config split_ratio       0.52

# # make windows float on specific desktops
# bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
# 	case "$desktop" in
# 		www|play|6|virt|7|9)
# 			bspc node "$nodeid" --state floating
# 			;;
# 	esac
# done &


# don't show borders or gaps in monocle mode
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus true
# bspc config ignore_ewmh_focus true 

# resize floating windows with the mouse !
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# color
# bspc config normal_border_color
# bspc config focused_border_color -- honestly ok with default
# TODO: color scheme?
bspc config presel_feedback_color '#1d2026'

# idea: named desktops for'dev', 'chat', 'editing', etc

# add hidden scratchpad
bspc rule -a dropdown sticky=on state=floating locked=on hidden=on
termite --class dropdown -e "zsh -i" e

bspc rule -a keys-help sticky=on state=floating 
